### ISSUE TITLE
Fedora 23

### ISSUE THREAD

**Issue by nk-87** [hugegreenbug/xf86-input-cmt#29]
Was wondering if there was a way to install this on Fedora? My c720p is unable to recognize the touchpad at all - was working fine with GalliumOS.

**Comment by hugegreenbug** [comment]
It can be installed on fedora. You would need to compile and install libevdevc, libgestures, and xf86-cmt-input.

Your problem would not be fixed by this driver, but by a patch that is missing from upstream kernels. This is the patch: https://github.com/GalliumOS/linux-patches/blob/master/chromos_laptop_elan.patch

**Comment by nk-87** [comment]
Sorry for the dumb question, but how would I apply that in Fedora if the Kernel version is different? (I'm on 4.4.6)
