### ISSUE TITLE
Australian Scrolling is broken

### ISSUE THREAD

**Issue by javelinanddart** [hugegreenbug/xf86-input-cmt#8]
Even though the option is set, it still has normal scrolling. I've also tried the natural scrolling option in GNOME's settings and that doesn't work either.

**Comment by hugegreenbug** [comment]
Make sure you have the right option. It has changed. The option is now: Australian Scrolling in the latest version. You can see if you have that option with xinput: 

xinput --list-props id  

where id is the id of your touchpad that you can find with just running: xinput

The Gnome settings won't work because it is designed for the Synaptics driver.

**Comment by javelinanddart** [comment]
Option          "Scroll Australian" "1"
is what I have set
if I change that to Australian Scrolling from Scroll Australian it will work?

**Comment by hugegreenbug** [comment]
It should.

Hugh

**Comment by javelinanddart** [comment]
Yep that worked, thank you!
